ShadowUFLocals = {
	-- Errors
	["Invalid tag used %s."] = "Invalid tag used %s.",
	["Cannot register layout %s, string or table expected for data got %s."] = "Cannot register layout %s, string or table expected for data got %s.",
	["Cannot register layout, no name passed."] = "Cannot register layout, no name passed.",
	["Cannot register tag, no name passed."] = "Cannot register tag, no name passed.",
	["Cannot register tag %s, string expected got %s."] = "Cannot register tag %s, string expected got %s.",
	["Cannot register layout, configuration should be a table got %s."] = "Cannot register layout, configuration should be a table got %s.",
	["Cannot register tag, data should be passed as {help = \"help text\", events = \"EVENT_A EVENT_B\", funct = \"function(unit) return \"Foo\" end}"] = "Cannot register tag, data should be passed as {help = \"help text\", events = \"EVENT_A EVENT_B\", funct = \"function(unit) return \"Foo\" end}",
	
	-- Layout text
	["Left text"] = "Left text",
	["Right text"] = "Right text",
	["Middle text"] = "Middle text",
	
	-- Tag text
	["Dead"] = "Dead",
	["Aggro"] = "Aggro",
	["Offline"] = "Offline",
	["Male"] = "Male",
	["Female"] = "female",
	["Rare"] = "Rare",
	["Ghost"] = "Ghost",
	["Elite"] = "Elite",
	["Rare Elite"] = "Rare Elite",
	["Boss"] = "Boss",
	
	-- GUI
	["Tags"] = "Tags",
	["Layout"] = "Layout",
	["Units"] = "Units",
		
	-- Tag help
	["Unit name colored by class."] = "Unit name colored by class.",
	["Units classification, Rare, Rare Elite, Elite, Boss, nothing is shown if they aren't any of those."] = "Units classification, Rare, Rare Elite, Elite, Boss, nothing is shown if they aren't any of those.",
	["Returns Offline if the unit is offline, otherwise nothing is shown."] = "Returns Offline if the unit is offline, otherwise nothing is shown.",
	["Level without any coloring."] = "Level without any coloring.",
	["Current health, uses a short format, 11500 is formatted as 11.5k, values below 10000 are formatted as is."] = "Current health, uses a short format, 11500 is formatted as 11.5k, values below 10000 are formatted as is.",
	["Amount of health missing, if none is missing nothing is shown. Uses a short format, -18500 is shown as -18.5k, values below 10000 are formatted as is."] = "Amount of health missing, if none is missing nothing is shown. Uses a short format, -18500 is shown as -18.5k, values below 10000 are formatted as is.",
	["Unit name"] = "Unit name",
	["Amount of power missing,  if none is missing nothing is shown. Uses a short format, -13850 is shown as 13.8k, values below 10000 are formatted as is."] = "Amount of power missing,  if none is missing nothing is shown. Uses a short format, -13850 is shown as 13.8k, values below 10000 are formatted as is.",
	["Max power, uses a short format, 16000 is formatted as 16k, values below 10000 are formatted as is."] = "Max power, uses a short format, 16000 is formatted as 16k, values below 10000 are formatted as is.",
	["Current and maximum power, formatted as [curpp]/[maxpp]."] = "Current and maximum power, formatted as [curpp]/[maxpp].",
	["Unit race, for a Blood Elf then Blood Elf is returned, for a Night Elf than Night Elf is returned and so on."] = "Unit race, for a Blood Elf then Blood Elf is returned, for a Night Elf than Night Elf is returned and so on.",
	["Returns the units sex."] = "Returns the units sex.",
	["Returns + if the unit is an elite or rare elite mob."] = "Returns + if the unit is an elite or rare elite mob.",
	["Returns current health as a percentage, if the unit is dead or offline than that is shown instead."] = "Returns current health as a percentage, if the unit is dead or offline than that is shown instead.",
	["Returns Rare if the unit is a rare or rare elite mob."] = "Returns Rare if the unit is a rare or rare elite mob.",
	["Current power, uses a short format, 12750 is formatted as 12.7k, values below 10000 are formatted as is."] = "Current power, uses a short format, 12750 is formatted as 12.7k, values below 10000 are formatted as is.",
	["Current and maximum health, formatted as [curhp]/[maxhp], if the unit is dead or offline then that is shown instead."] = "Current and maximum health, formatted as [curhp]/[maxhp], if the unit is dead or offline then that is shown instead.",
	["Short classifications, R for Rare, R+ for Rare Elite, + for Elite, B for boss, nothing is shown if they aren't any of those."] = "Short classifications, R for Rare, R+ for Rare Elite, + for Elite, B for boss, nothing is shown if they aren't any of those.",
	["Total number of combo points you have on your target."] = "Total number of combo points you have on your target.",
	["If the unit is dead, returns dead, if they are a ghost then ghost is returned, if they aren't either then nothing is shown."] = "If the unit is dead, returns dead, if they are a ghost then ghost is returned, if they aren't either then nothing is shown.",
	["Units status, Dead, Ghost, Offline, nothing is shown if they aren't any of those."] = "Units status, Dead, Ghost, Offline, nothing is shown if they aren't any of those.",
	["Returns current power as a percentage."] = "Returns current power as a percentage.",
	["Smart level, returns Boss for bosses, +50 for a level 50 elite mob, or just 80 for a level 80."] = "Smart level, returns Boss for bosses, +50 for a level 50 elite mob, or just 80 for a level 80.",
	["Units alignment, Thrall will return Horde, Magni Bronzebeard will return Alliance."] = "Units alignment, Thrall will return Horde, Magni Bronzebeard will return Alliance.",
	["Colored level by difficulty, no color used if you cannot attack the unit."] = "Colored level by difficulty, no color used if you cannot attack the unit.",
	["For players, it will return a class, for mobs than it will return their creature type."] = "For players, it will return a class, for mobs than it will return their creature type.",
	["Max health, uses a short format, 17750 is formatted as 17.7k, values below 10000 are formatted as is."] = "Max health, uses a short format, 17750 is formatted as 17.7k, values below 10000 are formatted as is.",
	["Colored class, use [class] for just the class name without coloring."] = "Colored class, use [class] for just the class name without coloring.",
	["Create type, for example, if you're targeting a Felguard then this will return Felguard."] = "Create type, for example, if you're targeting a Felguard then this will return Felguard.",
	["Class, use [classcolor] if you want a colored class name."] = "Class, use [classcolor] if you want a colored class name.",
}